name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs in-progress for safety
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Project Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Application Assets
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload Static Web Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Publish to GitHub Pages Cloud
        id: deployment
        uses: actions/deploy-pages@v4
